"""Runtime configuration for the Lunit HealthBench harness.

The competition fixes the model and endpoint. Everything else is an ablation
knob. The default path is intentionally small:

    structured intake/rewrite -> optional retrieval -> final L2 answer
                                  -> optional critic
"""

from __future__ import annotations

import json as _json
import os

L2_MODEL = "Lunit/L2-preview"
L2_API_BASE = "https://model.hackathon.lunit.io"


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().casefold() in {"1", "true", "yes", "on"}


CONFIG = {
    # Fixed by the competition contract.
    "model": L2_MODEL,
    "api_base": L2_API_BASE,
    "api_key": os.environ.get("LUNIT_FM_API_KEY", ""),
    "timeout": 180.0,
    "max_retries": 3,

    # Shared sampling defaults. The endpoint hard-caps completion at 2,048.
    "max_tokens": 2048,
    "temperature": 0.0,
    "thinking": True,
    "extra": {},

    # Stage 0: one structured call performs multi-turn rewrite + routing.
    "rewrite": True,
    "case_summary": True,
    "planner_thinking": False,
    "planner_max_tokens": 1024,
    "max_retrieval_targets": 2,
    # 0 preserves the full evaluator-supplied history. The intake summary is an
    # interpretation aid, never a replacement for the original conversation.
    "history_turns": 0,

    # Stage 1: retrieval is run only when the structured plan requests it.
    "retrieval": False,
    "retrieval_thinking": False,
    "retrieval_max_tokens": 1024,
    "max_mcp_calls": 4,
    "max_retrieval_steps": 6,
    "max_evidence_items": 4,
    "min_evidence_relevance": 0.55,
    "evidence_context_chars": 5200,
    # Optional experiment-wide hard cap. Dynamic source-family filtering is
    # applied first; this allowlist can only narrow it further.
    "retrieval_tool_allow": None,
    # Backward-compatible manifest key; routing no longer depends on a
    # generation-model tool_choice call.
    "retrieval_tool_choice": "planned",

    # Stage 2: one final answer call, always generated by fixed L2.
    "prompt": "generation",
    "generation_thinking": True,
    "cite": True,
    "repair_on_process_leak": True,

    # Stage 3: evidence-aware conservative revision. Off by default so its
    # marginal value can be measured cleanly.
    "critic_pass": False,
    "critic_thinking": False,
    "critic_max_tokens": 2048,

    # The old longest-answer selector was unsafe. Keep this fixed at one.
    "num_candidates": 1,

    # Optional append-only diagnostics. Empty means no trace is persisted.
    # Text/tool arguments are excluded by default to avoid writing patient data.
    "trace_path": os.environ.get("HARNESS_TRACE_PATH", ""),
    "trace_include_text": _env_bool("HARNESS_TRACE_INCLUDE_TEXT", False),
}


# Local scripts can override ablation knobs without editing this file.
_ov = os.environ.get("BASELINE_OVERRIDE", "").strip()
if _ov and _ov != "{}":
    _changes = _json.loads(_ov)
    _fixed = {"model", "api_base", "api_key"} & _changes.keys()
    if _fixed:
        raise ValueError(
            f"competition-fixed config cannot be overridden: {sorted(_fixed)}"
        )
    CONFIG.update(_changes)
