"""System configuration.  [AGENT MAY EDIT — this is the main knob board]

One commit = one changed knob. A diff of this file should read as the
experiment description.
"""

import os

CONFIG = {
    # ---- model (RULE: the final output must be generated by Lunit L2) -------
    "model": os.environ.get("LUNIT_FM_MODEL", "Lunit/L2-preview"),
    "api_base": os.environ.get("LUNIT_FM_API_URL", "https://model.hackathon.lunit.io"),
    "api_key": os.environ.get("LUNIT_FM_API_KEY", ""),
    "timeout": 180.0,
    "max_retries": 3,
    # ---- sampling ----------------------------------------------------------
    # max_tokens is capped at 2048 by the server and reasoning eats the same
    # budget.  thinking=False measured: -38% latency, +10% answer length.
    "max_tokens": 2048,
    "temperature": 0.0,
    "thinking": False,  # fallback for direct l2.chat() callers
    "extra": {},  # top_p / top_k / min_p / repetition_penalty
    # n>1 is REJECTED by the server ("n must be 1"); num_candidates below
    # issues that many independent requests instead.
    # ---- stage 1: planning and retrieval ----------------------------------
    "retrieval": True,
    "retrieval_tool_choice": "auto",  # auto | required
    "retrieval_thinking": False,
    "max_mcp_calls": 4,  # actual MCP calls; finalization is reserved
    "retrieval_timeout_s": 30.0,
    "retrieval_max_tokens": 1024,
    "retrieval_tool_allow": None,  # optional global intersection with route tools
    "route_max_bundles": 3,
    "max_subquestions": 6,
    "planner_max_tokens": 768,
    "planner_timeout_s": 12.0,
    # ---- stage 2: generation ----------------------------------------------
    # "none" disables the prompt; any other value is a filename stem.
    "prompt": "minimal",
    "generation_thinking": False,
    "cite": True,  # cite retrieved evidence as [1], [2]
    # ---- multi-turn --------------------------------------------------------
    "rewrite": True,  # structured query planning on every turn
    "case_summary": False,  # never replace the original three-turn history
    "history_turns": 0,  # 0 = pass full history verbatim
    # ---- post-generation ---------------------------------------------------
    "critic_pass": False,  # penalty-pattern defence pass
    "critic_thinking": False,
    "num_candidates": 1,  # >1 = N independent requests, then pick/merge
}


# --------------------------------------------------------------------------
# baseline.sh passes a JSON dict here so the ladder can be run without editing
# this file. Never used by the submission container.
import json as _json  # noqa: E402

_ov = os.environ.get("BASELINE_OVERRIDE", "").strip()
if _ov and _ov != "{}":
    CONFIG.update(_json.loads(_ov))
